# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Trent Schweitzer
title: Graduate Student, Research Assistant
email: info@tjschweitzer.tech
website: tjschweitzer.tech

# Social links
twitter_username: tjschweitzer
github_username:  tjschweitzer
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: tjs406
linkedin_username: tjschweitzer
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile1.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm a research assistant and teachers assistant while completing my M.S. in Computer Science at the Universit of Montana.
  
  Currently researching: Fire simulation modeling using [FDS](https://www.nist.gov/services-resources/software/fds-and-smokeview)

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Photography
   - Flying Drones
   - Board Games 

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
